name: Android Build and release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Set up Fyne Cross
      run: go install github.com/fyne-io/fyne-cross@latest

    - name: Build for Android
      run: |
        fyne-cross android

    - name: Read TOML and set env vars
      run: |
        APP_NAME=$(awk -F '=' '/Name/ {gsub(/"/, "", $2); print $2}' fyne-cross.toml | xargs)
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

    - name: Upload Android APKs
      uses: actions/upload-artifact@v2
      with:
        name: android
        path: |
          fyne-cross/dist/android/
          fyne-cross/dist/android-386/
          fyne-cross/dist/android-amd64/
          fyne-cross/dist/android-arm/
          fyne-cross/dist/android-arm64/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          android/android/${{ env.APP_NAME }}.apk
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}