name: Android Build and Release

on:
  release:
    types: [created]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Set up Fyne
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Build for Android
      run: |
        fyne package -os android -appID com.sanjay7178.openfortiap -icon Icon.png

    - name: Read TOML and set env vars
      run: |
        APP_NAME=$(awk -F '=' '/Name/ {gsub(/"/, "", $2); print $2}' FyneApp.toml | xargs)
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android
        path: ${{ env.APP_NAME }}.apk

  create-android-release:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
    - name: Download Android artifact
      uses: actions/download-artifact@v2
      with:
        name: android

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Android Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./${{ env.APP_NAME }}.apk
        asset_name: ${{ env.APP_NAME }}-android.apk
        asset_content_type: application/vnd.android.package-archive
