name: Linux Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Set up Fyne Cross
      run: go install github.com/fyne-io/fyne-cross@latest

    - name: Build for Linux
      run: fyne-cross linux

    - name: Read TOML and set env vars
      run: |
        APP_NAME=$(awk -F '=' '/Name/ {gsub(/"/, "", $2); print $2}' FyneApp.toml | xargs)
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: fyne-cross/dist/linux-amd64/

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux Artifact
      uses: actions/download-artifact@v2
      with:
        name: linux

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: fyne-cross/dist/linux-amd64/${{ env.APP_NAME }}.tar.xz
